# Generated by Django 4.0.6 on 2022-09-20 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PokemonsBBDD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('categoria', models.CharField(max_length=200)),
                ('habilidades', models.IntegerField()),
                ('dano', models.IntegerField()),
                ('img', models.ImageField(upload_to='images')),
            ],
        ),
    ]
