# Generated by Django 4.0.6 on 2022-09-21 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemonsbbdd',
            name='img',
            field=models.ImageField(upload_to='img'),
        ),
    ]
