# Generated by Django 4.0.6 on 2022-09-21 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_pokemonsbbdd_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemonsbbdd',
            name='habilidades',
            field=models.CharField(max_length=250),
        ),
    ]
