# Generated by Django 4.0.6 on 2022-10-04 02:30

from django.db import migrations, models
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_pokemonsbbdd_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemonsbbdd',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=projects.models.upload_to, verbose_name='images'),
        ),
    ]
